feat: Add better changes summary helper (#2240)
#### Summary

Part of https://linear.app/cloudquery/issue/ENG-1828/feat-improved-forced-migration-needed-error-message.

Open for feedback, I tried to keep only the most interesting bit of each change. There's another improvement to be made and that's to pass only the breaking changes to the summary function (at the moment plugins print all changes which adds additional noise)

## Before

```
Loading spec(s) from examples/gcp_to_postgres.yml
Starting migration for: gcp (cloudquery/gcp@v18.20.1) -> [postgresql (cloudquery/postgresql@v8.6.5)]
Error: failed to migrate v3 source gcp: rpc error: code = Internal desc = write failed: tables gcp_compute_routes,gcp_artifactregistry_docker_images with changes [[column: next_hop_inter_region_cost, type: add, current: next_hop_inter_region_cost:int64 column: next_hop_med, type: add, current: next_hop_med:int64 column: next_hop_origin, type: add, current: next_hop_origin:utf8 column: tags, type: update, current: tags:json, previous: tags:list<item: utf8, nullable>] [column: tags, type: update, current: tags:json, previous: tags:list<item: utf8, nullable>]] require migration. Migrate manually or consider using 'migrate_mode: forced'
```

## After

```
Loading spec(s) from examples/gcp_to_postgres.yml
Starting migration for: gcp (cloudquery/gcp@v18.20.1) -> [postgresql (grpc@localhost:8888)]
Error: failed to migrate v3 source gcp: rpc error: code = Internal desc = write failed: 
Can't migrate tables automatically, migrate manually or consider using 'migrate_mode: forced'. Non auto migratable tables changes:

gcp_artifactregistry_docker_images:
  - Type changed from "list<item: utf8, nullable>" to "json" for column "tags"

gcp_compute_routes:
  - Column "next_hop_inter_region_cost" added with type "int64"
  - Column "next_hop_med" added with type "int64"
  - Column "next_hop_origin" added with type "utf8"
  - Type changed from "list<item: utf8, nullable>" to "json" for column "tags"
```

---